#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
    hibernate:
      ddl-auto: create-drop
    properties:
      default_batch_fetch_size: 20
      jdbc.batch_size: 20
      id.new_generator_mappings: false
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
  datasource:
    # ImMemory
    url: jdbc:h2:mem:voting
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:voting
    # Absolute path
    #    url: jdbc:h2:C:/projects/bootjava/restorant-voting/db/voting
    #    tcp: jdbc:h2:tcp://localhost:9092/C:/projects/bootjava/restorant-voting/db/voting
    # Relative path form current dir
    #    url: jdbc:h2:./db/voting
    # Relative path from home
    #    url: jdbc:h2:~/voting
    #    tcp: jdbc:h2:tcp://localhost:9092/~/voting
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
  #  security:
  #    user:
  #      name: user
  #      password: password
  #      roles: USER
  cache:
    cache-names: users, menu, restaurants
    caffeine.spec: maximumSize=5000,expireAfterAccess=600s
logging:
  level:
    root: WARN
    topjava.restaurantvoting: DEBUG
    org.springframework.security.web.FilterChainProxy: WARN
    org.hibernate: INFO
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
  file:
    name: application.log
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p})  %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server.servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
